export enum CONFIG_KEYS {
  NODE_ENV = 'NODE_ENV',
  DB_URL = 'DB_URL',
  PORT = 'PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_HOSTNAME = 'DB_HOSTNAME',
  DB_PORT = 'DB_PORT',
  SYSTEM_NAME = 'SYSTEM_NAME',
  SYSTEM_DESCRIPTION = 'SYSTEM_DESCRIPTION',
  VERSION = 'VERSION',
  WEB_URL = 'WEB_URL',
  JWT_SECRET = 'JWT_SECRET',
}

export enum DB_COLLECTIONS {
  USERS = 'users',
  ACCESS_CREDENTIALS = 'access_credentials',
  REFRESH_TOKENS = 'refresh_tokens',
}
